config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'static_pages/home'

  get 'static_pages/help'

  get "static_pages/about"

  get "static_pages/contact"

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Возвращает полный заголовок зависящий от страницы # Документирующий комментарий
  def full_title(page_title)                          # Определение метода
    base_title = "Ruby on Rails Tutorial Sample App"  # Назначение переменной
    if page_title.empty?                              # Булевый тест
      base_title                                      # Явное возвращение
    else
      "#{base_title} | #{page_title}"                 # Интерполяция строки
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "sample app", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home", static_pages_home_path %></li>
              <li><%= link_to "Help", static_pages_help_path %></li>
              <li><%= link_to "Contacts", static_pages_contact_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>Страница о нас</h1>

<p>Страницу можно найти на app/views/static_pages/about.html.erb</p>
<p>
«Сотрудники Пятого канала живы и здоровы»,- заявил радиостанции «Говорит Москва» руководитель пресс-службы погрануправления ФСБ по Ростовской области Василий Малаев.

</p>

<p>
По предварительным данным, с территории Украины был обстрелян российский пункт пропуска «Донецк», когда там были сотрудники Пятого канала, которые делали репортаж об украинских беженцах. 
<p>
Вице-премьер отметил, что уже выбраны параметры будущего транспортного перехода и поставлена задача по оптимизации его стоимости.
</p>
<p>
Вместе с пограничниками и журналистами на пропускном пункте находилась оперативно-следственная группа. Правоохранители устанавливали обстоятельства атаки российской территории минувшей ночью. 
</p>

<p>
Перейти к странице <%= link_to "Home", static_pages_home_path %>
</p>

    <p>
      The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      is a project to make a book and screencasts to teach web development
      with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
      is the sample application for the tutorial.
    </p>

app/views/static_pages/contact.html.erb
<div class="center hero-unit">
<h1>Наши контакты</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

</div>

<p>
Владимиру Кулишову инкриминируют финансирование и поддержку терроризма на украинской территории. Об этом заявил глава Службы безопасности Украины Валентин Наливайченко.
</p>

<p>
Перейти к странице <%= link_to "Home", static_pages_home_path %>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Страница Help</h1>
<p>Страницу можно найти на app/views/static_pages/help.html.erb</p>
<p>
Ряд российских и зарубежных компаний уже заявили о готовности приступить к его возведению, сообщил зампред правительства Дмитрий Козак
</p>

<p>
Он напомнил, что эти работы войдут в федеральную целевую программу по социально-экономическому развитию Крымского федерального округа до 2020 года. Они станут существенной составляющей её расходной части.
</p>

<p>
Вице-премьер отметил, что уже выбраны параметры будущего транспортного перехода и поставлена задача по оптимизации его стоимости.
</p>

<p>
Компанию, которой доверят строительство, определят по результатам конкурса. Его ещё предстоит провести.
</p>

<p>
Мост через Керченский пролив напрямую свяжет Краснодарский край с Крымом. Сейчас добраться на полуостров можно либо через территорию Украины, либо через пролив на пароме.
</p>

<p>
Перейти к странице <%= link_to "Home", static_pages_home_path %>
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>


<p>
Страница находится на app/views/static_pages/home.html.erb
</p>

<p>
Владимиру Кулишову инкриминируют финансирование и поддержку терроризма на украинской территории. Об этом заявил глава Службы безопасности Украины Валентин Наливайченко.

Ранее стало известно, что по аналогичным статьям открыто уголовное производство против гендиректора агентства «Россия сегодня» Дмитрия Киселёва. Сам Киселёв считает эти обвинения «продолжением фантазий киевских властей».

</p>

<p>
Перейти к странице <%= link_to "Help", static_pages_help_path %>
</p>

<p>
Перейти к странице <%= link_to "About", static_pages_about_path %>
</p>

<p>
Перейти к странице <%= link_to "Contact", static_pages_contact_path %>
</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>